version: "3.1"

services:
  database:
    build: 
       context: database
    image: ci_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: ddev
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password

  api:
    build:
       context: api
    image: ci_api
    ports:
      - "8081:8080"
      - "5005:5005"
    networks:
      - back-tier
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
    
networks:
  back-tier:
